name: benson-shoe-management
build:
  - composer install --no-dev --optimize-autoloader
  - rm -rf node_modules package-lock.json
  - npm install
  - npm run build
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

deploy:
  - php artisan migrate --force

environments:
  production:
    build:
      - composer install --no-dev --optimize-autoloader
      - rm -rf node_modules package-lock.json
      - npm install
      - npm run build
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
    deploy:
      - php artisan migrate --force
