name: benson-shoe-management
build:
  - composer install --no-dev --optimize-autoloader
  - npm ci
  - npm run build
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

deploy:
  - php artisan migrate --force
  - php artisan db:seed --force

environments:
  production:
    build:
      - composer install --no-dev --optimize-autoloader
      - npm ci
      - npm run build
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
    deploy:
      - php artisan migrate --force
