# For more information: https://laravel.com/docs/sail
services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.3/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      PHP_CLI_SERVER_WORKERS: 4
      OPCACHE_ENABLE: 1
      COMPOSER_PROCESS_TIMEOUT: 2000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    volumes:
      - ".:/var/www/html:cached"
      - "./storage/logs:/var/www/html/storage/logs:delegated"
      - "./storage/framework:/var/www/html/storage/framework:delegated"
      - "./storage/app:/var/www/html/storage/app:delegated"
      - "./vendor:/var/www/html/vendor:delegated"
      - "./node_modules:/var/www/html/node_modules:delegated"
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    deploy:
      resources:
        limits:
          memory: 1G
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=512M
      - --table-definition-cache=2000
      - --performance-schema=OFF
      - --bind-address=0.0.0.0
      - --socket=/tmp/mysql.sock
    networks:
      - sail
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${FORWARD_PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      # Add these environment variables to increase max execution time
      UPLOAD_LIMIT: 300M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    networks:
      - sail
    depends_on:
      - mysql

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sail-redis:/data:delegated"
    deploy:
      resources:
        limits:
          memory: 512M
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
